<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit55ac8c947bf1b79848a158cfa238e775
{
    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'App\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'App\\' => 
        array (
            0 => __DIR__ . '/../..' . '/app',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit55ac8c947bf1b79848a158cfa238e775::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit55ac8c947bf1b79848a158cfa238e775::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit55ac8c947bf1b79848a158cfa238e775::$classMap;

        }, null, ClassLoader::class);
    }
}
